import './lang-auto.js';
// import './auth.js';
//import './login.js';
import './auth-ui.js';
import './main.js';
import './menuHamburguesa.js';
import './search.js';
import './acc&sett.js';
import './dark.js';
import './crear.js';
import './editar.js';
import './firebase.js';
